export default {
    EMAIL: "Email",
    NAME: "Nama",
    PASSWORD: "Password",
    PHONE: "No. Telp",
    LOGIN: "Login",
    LOGOUT: "Logout",
    SIGNUP: "Daftar",
    HOME: "Home",
    CREATE_ACCOUNT: "Buat Akun",
    DOCTOR_SCHEDULE: "Jadwal Dokter",
    REGISTER: "Register",
    RESERVATION: "Reservasi",
    RESERVATION_HISTORY: "Riwayat Reservasi",
    CREATE_RESERVATION: "Buat Reservasi",
    PROFILE: "Profil",
    EDIT_PROFILE: "Ubah Profil",
    HISTORY: "Riwayat",
    MEDICAL_HISTORY: "Riwayat Pemeriksaan",
    CANCEL: "Batal",
    SETTINGS: "Pengaturan",
    SCHEDULE: "Jadwal",
    UPCOMING_SCHEDULE: "Jadwal Mendatang",
    CLINIC: "Klinik",
    DOCTOR: "Dokter",
    DATE: "Tanggal",
    TIME: "Waktu",
    CHOOSE_CLINIC: "Pilih Klinik",
    CHOOSE_DATE: "Pilih Tanggal",
    CHOOSE_DOCTOR: "Pilih Dokter",
    CHOOSE_BY: "Pilih Berdasarkan",
    NOTES: "Catatan",
}